# Generated by Django 3.2.15 on 2023-03-20 16:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0003_auto_20230320_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbookrelation',
            name='book',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='store.book'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userbookrelation',
            name='in_bookmarks',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userbookrelation',
            name='like',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userbookrelation',
            name='rate',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Ok'), (2, 'Fine'), (3, 'Good'), (4, 'Amazing'), (5, 'Incredible')], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userbookrelation',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
    ]
